### ISSUE TITLE
安装agent时，windows系统certutil 命令和powershell命令顺序会发生变化，linux和mac系统curl和wget命令顺序也会发生变化

### ISSUE THREAD

**Issue by axingde** [TophantTechnology/Daybreak#5]
以windows系统为例，点击安装探针，默认是amd64架构，在不同架构选择几次后，安装命令顺序会发生变化，linux和mac系统同样如此
![image](https://user-images.githubusercontent.com/65204372/208572340-d71e4be1-9138-4514-a7b8-1d7bfe7a25ac.png)

![image](https://user-images.githubusercontent.com/65204372/208572384-e4570b1e-3233-4432-8d80-d9eb995bc8b8.png)

**Comment by 1c3z** [comment]
感谢反馈。

**Comment by 1c3z** [comment]
已经修了。 可以下载新版本。

https://daybreak.tophant.com/home
